---
 - name: install gcc
   yum:
    name: gcc
    state: present

 - name: install gcc-c++
   yum:
    name: gcc-c++
    state: present

 - name: install pcre-devel
   yum:
    name: pcre-devel
    state: present

 - name: openssl-devel
   yum:
    name: openssl-devel
    state: present

 - name: expat-devel
   yum:
    name: expat-devel
    state: present
...