---
 - name: stransfer sql to remote host
   template: 
    src: ../template/master_slaves.sql
    dest: /tmp/master_slaves.sql

 - name: create replication user on master / start slave on slave
   when:
   shell: mysql -hlocalhost -uroot -p{{ mysql_root_password }} -S /tmp/mysql.sock < /tmp/master_slaves.sql

 - name: clear temp file tmp/master_slaves.sql
   file:
    dest: tmp/master_slaves.sql
    state: absent
