  - name: config systemd
    import_tasks: common/config_mysql_systemd.yaml
    when: ansible_distribution_major_version == "7"

  - name: start mysql(sytemctl)
    shell: systemctl start mysql
    when: ansible_distribution_major_version == "7"

  - name: config mysql.service start up on boot
    when: ansible_distribution_major_version == "7"
    shell: systemctl enable mysql

  - name: config sysv start script
    when: ansible_distribution_major_version == "6"
    copy:
     remote_src: yes
     src: "{{mysql_base_dir + 'support-files/mysql.server'}}"
     dest: /etc/init.d/mysqld
     mode: 0755

  - name: start mysql(service)
    when: ansible_distribution_major_version == "6"
    service: 
    name: mysqld
    state: started

  - name: config mysql.service start up on boot
    when: ansible_distribution_major_version == "6"
    shell: chkconfig mysqld on